#!/usr/bin/env bash
JOB_COUNT=$BUILDKITE_PARALLEL_JOB_COUNT JOB_INDEX=$BUILDKITE_PARALLEL_JOB yarn test --testMatch=$(node get-test-files.js) || exit 1
bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json -n node
