#!/usr/bin/env bash
node --max-old-space-size=4096 ./node_modules/.bin/nyc --reporter=text --reporter=json yarn test || exit 1
bash <(curl -s https://codecov.io/bash) -f coverage/coverage-final.json -n node
